version: "3.9"
services:
  citypulse-health:
    build:
      context: ..
      dockerfile: devops/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      PORT: "8000"
